### ISSUE TITLE
zigi does not detect edits of PS dataets when done "outside of" zigi

### ISSUE THREAD

**Issue by wizardofzos** [wizardofzos/zigi#123]
Adding will not work then. You'd have to edit it from within zigi, force a save.. then it works

**Comment by daveyc** [comment]
Why not use a CRC32 or SHA-1? Trouble is you will need somewhere to stash the hashes like git does in the file system!

**Comment by wizardofzos** [comment]
Fixed in v1r1-rc , FINing the issue
