### ISSUE TITLE
Incorrect call to routine

### ISSUE THREAD

**Issue by jaytay79** [wizardofzos/zigi#130]
Steps to reproduce:
I created a new repo then performed a `touch README.MD` in the USS directory, back in zigi I selected the Refresh option and then this happened:

```
   855 +++            ckothlq = subword(ckothlq,1,qualignr)
   447 +++         call Refresh localrep zigirep pdshlq qualignr
  1116 +++     call work_with_repo
   311 +++   call Create_Repo
IRX0040I Error running ZIGI, line 855: Incorrect call to routine
***
```

**Comment by wizardofzos** [comment]
Did you add any datasets to the repo before doing that. Or was it still “bare”

**Comment by jaytay79** [comment]
Very bare, which is probably the root cause!

**Comment by jaytay79** [comment]
On a related topic, adding a dataset to a new repo gives me some oddities. I added a dataset ‘ZIGI.TEST’ which is a PDS containing one member but zigi itself shows the below - ZIGI.DSNB doesn’t exist:

```
S  Status                    Dataset Name
   Ý??¨ Untracked            'ZIGI.DSNB'
```

**Comment by wizardofzos** [comment]
Wtf ;)
I’ll get into that tomorrow. Just to check. This is on master not the 1.1rc?

**Comment by lbdyck** [comment]
@jaytay79 - was this using the master branch or the 1.1rc branch - I'm not able to recreate using the 1.1rc branch.
 
Note: 1.1rc branch has *many* improvements and bug fixes over the master. It just needs more checkout before it loses the rc.

**Comment by wizardofzos** [comment]
Also jim : what was your “ignore” setting when adding?

**Comment by jaytay79** [comment]
@lbdyck It was the master - I will try it again on the 1.1 branch later and let you know. The ignore would be whatever the default is I guess! Again I can check this later for you.

**Comment by wizardofzos** [comment]
Got the bug from someone else too ;)
fixed the 'ZIGI.DSNB' issue (you had ignore 0)
keeping issue open until v1r1-rc hits master

**Comment by lbdyck** [comment]
Should be fixed in v1r1-rc
