### ISSUE TITLE
Possible information leakage in commitmsg

### ISSUE THREAD

**Issue by mfsysprog** [wizardofzos/zigi#140]
The commitmessage for .gitattributes that is autogenerated when creating a new repo adds jobname (most of the time the userid) and the sysname. If this is pushed to a public remote repo it might lead to unintended information leakage. 
commitmsg = "added by zigi v1r0 for "
    commitmsg = commitmsg || MVSVAR('SYMDEF','JOBNAME')
    commitmsg = commitmsg || " on "
    commitmsg = commitmsg || MVSVAR('SYSNAME')

Suggest to remote both jobname and sysname from the message.

**Comment by wizardofzos** [comment]
Fixed in v1r1 :)
