### ISSUE TITLE
change refresh menu option/command to replace

### ISSUE THREAD

**Issue by mfsysprog** [wizardofzos/zigi#154]
The refresh command/menu option will replace the contents of the mvs dataset. This might come as an unpleasant surprise to a lazy user like myself. Even though the comment with the refresh option clearly indicates that it will do a replace, I would strongly suggest to change the command to 'replace' instead of 'refresh'

**Comment by lbdyck** [comment]
What about a prompt to confirm the user really wants to do a refresh as a way of confirmation?

**Comment by mfsysprog** [comment]
that would work too I guess
