### ISSUE TITLE
After branching the panel is not updated...

### ISSUE THREAD

**Issue by wizardofzos** [wizardofzos/zigi#188]
I just switched to a different branch, yet the text on the panel is unchanged...
![Screenshot from 2019-12-17 21-18-45](https://user-images.githubusercontent.com/117615/71031035-e7c81980-2112-11ea-83a8-9030f1169be6.png)
See difference in remote path and current branch...

**Comment by lbdyck** [comment]
I was unable to recreate in the 2.0 dev branch
