### ISSUE TITLE
Delete Repo Question

### ISSUE THREAD

**Issue by wizardofzos** [wizardofzos/zigi#189]
Lionel,

What's the diff with OMVS and git delete? Haven't checked code yet. But it's confusing me :)
![Screenshot from 2019-12-17 21-22-23](https://user-images.githubusercontent.com/117615/71031315-6fae2380-2113-11ea-8dc7-16fddd6c059d.png)

**Comment by lbdyck** [comment]
Git delete removes from git while omvs removes from omvs filesystem.

--------------------------------------------
Lionel B. Dyck <sdg>
Senior Software Engineer
21st Century Software
940 West Valley Road
Suite 1604
Wayne, PA 19087
www.21stcenturysoftware.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.21stcenturysoftware.com&d=DwMFAw&c=jf_iaSHvJObTbx-siA1ZOg&r=O9Yt-0q7UsiUaBSmIwennw&m=ze6XIIO6XqAm_rFtn1zF8hbYK-3sN7_ZCV0uDjSUFWI&s=C0xITJTTxnixxEtO9UXS82AE82iV9VszD9838jfcEcs&e=>

lioneld@21csw.com<mailto:lioneld@21csw.com>
(800) 555-6845  x610
(610) 710-4832 – Office

From the Leaders in Data Stewardship™

THIS E-MAIL MAY CONTAIN PRIVILEGED, CONFIDENTIAL, COPYRIGHTED, OR OTHER LEGALLY PROTECTED INFORMATION. IF YOU ARE NOT THE INTENDED RECIPIENT (EVEN IF THE E-MAIL ADDRESS ABOVE IS YOURS), YOU MAY NOT USE, COPY, OR RE-TRANSMIT IT. IF YOU HAVE RECEIVED THIS BY MISTAKE PLEASE NOTIFY US BY RETURN E-MAIL, THEN DELETE. THANK YOU
