### ISSUE TITLE
EDC5129I  messages 

### ISSUE THREAD

**Issue by markons** [wizardofzos/zigi#193]
Message EDC5129I will be generated in some situations:

"fatal: cannot run less: EDC5129I No such file or directory. "
or
"fatal: could not read log file 'zigitest/cmsg473': EDC5129I No such file or directory"

However, the related command will be (mostly) executed.

Another issue: the command BASIC seems not to work in our installation. I have renamed this into "BASIX" in panels and Rexx, now it is OK. But as told, it can be a local problem.

**Comment by lbdyck** [comment]
Thank you - for BASIC being an issue it sounds like your site may have BASIC defined in your ISPF command table and that is taking ownership of it. Fortunately BASIC is just an alias of PRO and MENU so you can use any of those.

Perhaps changing PRO and BASIC to MENU in the panels would be simpler?  Thoughts?

**Comment by markons** [comment]
Thank you Lionel - the BASIC problem is solved.
However, I have still some comical messages at ADDing files to my repo. See the attached screenshot.
![zigi-messages-at-add](https://user-images.githubusercontent.com/2115566/71714788-74f7b780-2e0f-11ea-8b7e-56634724e10c.png)
