### ISSUE TITLE
Support for different code pages

### ISSUE THREAD

**Issue by mgrossmann** [wizardofzos/zigi#196]
Hey @wizardofzos / @lbdyck 

actually I wanted to deal with [Issue #194](https://github.com/wizardofzos/zigi/issues/194) this weekend. Unfortunately a more important topic came up. The multilingualism. We have panels in more than four languages. So we have to be able to support code pages other than 1047. If I understand it correctly, the .gitattributes file could be used to set the right tags at folder or filename level. 

So, we only need a concept for zIGI to set the right values?! Is this right?

Maybe an default option plus some kind of filter:

```
**.**(*)=IBM-1047
ISPPLIB(PG*)=IBM-1141 #germanCP
ISPPLIB(PF*)=IBM-1147 #franceCP
```

Best regards Mike

**Comment by wizardofzos** [comment]
Yes, that would totally work. You'd need to change and add the .gitattributes file (as created by zigi)before adding any of the datasets and it should be golden.
Be advised though that the 'filter' in the .gitattributes files should match the 'USS-version' of the members, so in your example:

```
ISPPLIB/PG* git-encoding=iso8859-1 zos-working-tree-encoding=ibm-1141 
ISPPLIB/PF* git-encoding=iso8859-1 zos-working-tree-encoding=ibm-1147
```
Unless you need other git-encodings than iso8859-1 that is...
