### ISSUE TITLE
Abend during adding a dataset

### ISSUE THREAD

**Issue by mgrossmann** [wizardofzos/zigi#199]
hi guys,

I'm in trouble adding some datasets to the zigi repo.

```
System abend code 0C6, reason code 00000006.
Abend in host command LMMSTATS or address environment routine ISPEXEC.
System abend code 0C6, reason code 00000006.
Abend in host command %zigista or address environment routine TSO.
System abend code 0C6, reason code 00000006.
Abend in host command Select or address environment routine ISPEXEC.
```

If I allocate a new dataset with exactly the same attributes and copy the members into it, 
I can easily add this new dataset to the repo. 

Do you have any idea what this can be?

Best regards
Mike

**Comment by lbdyck** [comment]
Can you please share the steps to recreate this?  I presume this is on a new clone? 
Also which branch are you working with?

**Comment by mgrossmann** [comment]
Hello Lionel,

Unfortunately, you can't reproduce it. I guess the 06c happens when reading the dataset attributes / stats. As already said, if I create new datasets with the same allocation attributes, everything works fine. So,  I would like to postpone this issue until later.

Ty

**Comment by lbdyck** [comment]
can you try with the binary-feature branch or the v2r0-test branch?

**Comment by mgrossmann** [comment]
Lionel,

trying to add a dataset with BRANCH v2r0-test abends, too:

![image](https://user-images.githubusercontent.com/784509/72618960-89be6a00-393c-11ea-98f8-a98ac33e2c20.png)

**Comment by mgrossmann** [comment]
I was able to solve the problem. I was missing permissions on the dataset I wanted to add. Why this leads to a 0C6, only God and IBM know.

Issue could be closed.

Ty

**Comment by lbdyck** [comment]
cool - good to know

**Comment by lbdyck** [comment]
Since you have this resolved I'll close the issue.
