### ISSUE TITLE
Pull request fails

### ISSUE THREAD

**Issue by zszabo14** [wizardofzos/zigi#204]
I tried to pull from the remote. The file pulled to HFS, but synced with PDS. Prefix problem.
![image](https://user-images.githubusercontent.com/42870072/72600795-98912680-3914-11ea-882b-643f7a338006.png)

**Comment by zszabo14** [comment]
Pull with V2.0-test version:
 
INVALID DATA SET NAME, '.HU05849.JCL'                                  
    876 *-*           if x = 0                                          
        >V>             "16"                                            
        >L>             "0"                                             
        >O>             "0"                                             
 +++ Interactive trace.  TRACE OFF to end debug, ENTER to continue. +++

**Comment by wizardofzos** [comment]
Did you 'prefix'  the clone?

I see it prefixed with a '0'  That's not a valid HLQ :)


Met vriendelijke groeten,

*Henri Kuiper*
*zdevops B.V.*

*Keeping the "z" in Enterprise IT*

[image: Inline image 1] <http://nl.linkedin.com/in/wizardofzos>



*T* +31 6 392 1957 4
henrikuiper@zdevops.com
http://zdevops.com
@henrikuiper: <https://twitter.com/intent/tweet?text=@henrikuiper:>@zdevops:
<https://twitter.com/intent/tweet?text=@zdevops:>

U kunt vanaf dit adres ook mail van mij ontvangen vanuit mijn rol als
Technical Coordinator van de GSE. Meer informatie op http://gsenl.org

**Comment by zszabo14** [comment]
I created a new local repo. then added a PDS, then commit and push, then added a remote repo, push, then edited the JCL on the git web, then tried to pull.
Where I should prefix it?

**Comment by lbdyck** [comment]
![Snag_a3dd266](https://user-images.githubusercontent.com/42328411/72617024-ba32e380-38fd-11ea-9cbe-377f0ed01aae.png)
![Snag_a3deec8](https://user-images.githubusercontent.com/42328411/72617030-bef79780-38fd-11ea-80b6-9c4acf14014f.png)
![Snag_a3e0667](https://user-images.githubusercontent.com/42328411/72617035-c28b1e80-38fd-11ea-8c0a-9d2c6c54afc2.png)
![Snag_a3e1720](https://user-images.githubusercontent.com/42328411/72617043-c4ed7880-38fd-11ea-8a5b-ad9eeae6e17a.png)
![Snag_a3e276c](https://user-images.githubusercontent.com/42328411/72617050-c74fd280-38fd-11ea-8a70-680840387bf7.png)
![Snag_a3e38c1](https://user-images.githubusercontent.com/42328411/72617055-cae35980-38fd-11ea-9e84-a6397625e80c.png)
![Snag_a3e5429](https://user-images.githubusercontent.com/42328411/72617057-ce76e080-38fd-11ea-9cc4-76eaf784b84a.png)
![Snag_a3e725f](https://user-images.githubusercontent.com/42328411/72617068-d2a2fe00-38fd-11ea-93e5-95aec534f436.png)
![Snag_a3e849f](https://user-images.githubusercontent.com/42328411/72617072-d59dee80-38fd-11ea-9fa1-21018637e76e.png)

**Comment by lbdyck** [comment]
hope the above helps - if I missed a step that you were doing let me know

**Comment by zszabo14** [comment]
Thy

after this sreen I run AddDsn again. and that screen was 'empty'
![image](https://user-images.githubusercontent.com/42870072/72617320-02bbc280-3939-11ea-948b-1225a9b352b4.png)

**Comment by zszabo14** [comment]
Even after the first add, the prefix not stored in the repo config (I guess in the ISPFPROF)
![image](https://user-images.githubusercontent.com/42870072/72617785-09970500-393a-11ea-9633-b70f6e97042d.png)

**Comment by lbdyck** [comment]
can you reach me on skype?

**Comment by zszabo14** [comment]
> 
> 
> can you reach me on skype?

I have no skype :(

**Comment by zszabo14** [comment]
I started to create screenshots of my sequence...and now it works. Strange.....I changed nothing.

**Comment by zszabo14** [comment]
[sq.docx](https://github.com/wizardofzos/zigi/files/4077194/sq.docx)

**Comment by zszabo14** [comment]
as i see the my issues are mixed, last comments are for the other one

**Comment by lbdyck** [comment]
Read the docx and i was able to recreate - working on it

**Comment by lbdyck** [comment]
fixed in the v2r0-test branch

**Comment by zszabo14** [comment]
Good job! Thank You!

**Comment by lbdyck** [comment]
I found a few other places that needed to be updated for this issue.  Can you please pull the latest v2r0-test branch update and test again.  Let us know.

Thank you

**Comment by zszabo14** [comment]
i tested (just quickly) and works
