### ISSUE TITLE
Adding new PDS to an existing repo

### ISSUE THREAD

**Issue by zszabo14** [wizardofzos/zigi#205]
I created a local repo and added a Library, but when I’m trying to add a new one the screen is empty.
![image](https://user-images.githubusercontent.com/42870072/72600941-c9715b80-3914-11ea-9486-fdceefff1426.png)

**Comment by zszabo14** [comment]
HLQ missing on the Branch commad screen also

                                  
 Current Repository :  MCSGIT     
 Current HLQ        :             
 Current Branch     :  master

**Comment by lbdyck** [comment]
please start clean with v2r0-test branch and let us know.

**Comment by zszabo14** [comment]
> 
> 
> please start clean with v2r0-test branch and let us know.

Hi, cleaned, reinstalled. The issue is still on. 
1. Created a new repo. 
2. with AddDsn is added one PDS. 
3. Then quit the screen with F3, 
4. AddDsn again but the prefix field is not editable and the list of DSs is empty.

**Comment by lbdyck** [comment]
are there datasets under the prefix that you used - use ispf 3.4 on that prefix.  if none then that would explain it.  i'm reaching here i know but this is what it appears.

**Comment by zszabo14** [comment]
datasets are there, ther first AddDsn works

**Comment by lbdyck** [comment]
found a bug where if you enter a bad prefix the 1st time then you can't change it even if you update the panel.  fixed in the v2r0-test branch
