### ISSUE TITLE
New user onboarding

### ISSUE THREAD

**Issue by wizardofzos** [wizardofzos/zigi#218]
Need to add to the 'git config panel' the following fields:

- Default Push on commit (Y/N)
- Change ISPF UserID before commit to...

Should be part of flow where user enters git username and email. Maybe also add default PREFIX for checkouts to USERID()

**Comment by lbdyck** [comment]
Great idea....

**Comment by lbdyck** [comment]
Correction - this is dependent upon each repository.  The userid may be different for sure between each repo.  Default push may also be specific.

**Comment by lbdyck** [comment]
A suggestion - call the routine that displays the zigirset panel as part of the CLONE and CREATE process.  That should work and allows it to be unique to each repository.

**Comment by lbdyck** [comment]
Clone and Create panels updated for these options.  Will be in next push to v2r0-lionel
