### ISSUE TITLE
NOPREFIX user errors

### ISSUE THREAD

**Issue by wizardofzos** [wizardofzos/zigi#226]
Weird allocation wen TSO NOPREFIX is set, and CKOT tries to allocate for reading the .dsn file
![Screenshot from 2020-01-23 22-42-41](https://user-images.githubusercontent.com/117615/73028415-c48d3a00-3e35-11ea-99e5-903828daeced.png)

**Comment by lbdyck** [comment]
Fixed in v2r0-lionel

**Comment by lbdyck** [comment]
it wasn't fixed but I think it is now - please verify

**Comment by wizardofzos** [comment]
Verified. Did not quite work, but I've made it work...just a small addition to your fix :)
