### ISSUE TITLE
Status not updated after pull :(

### ISSUE THREAD

**Issue by wizardofzos** [wizardofzos/zigi#230]
When doing a pull the status is not updated to show that we're currently no behind the remote branch anymore...

**Comment by lbdyck** [comment]
I can't recreate this - do you have a scenario?

**Comment by wizardofzos** [comment]
Yeah...

1. Clone a repo (or create and push one)
2. Make sure there is a REMOTE change on the branch you're in
3. Get back into repo with zigi
4. Status field shows "You're behind ............ by 1 commit and can be fast forwarded"
5. Do a PULL
6. Status field stays the same

**Comment by lbdyck** [comment]
ok - so unique to that as I used an existing repo, made a commit/push from one system and then a pull from another system where it showed behind.  after the pull it was ok.

**Comment by lbdyck** [comment]
tried and can't recreate - using the latest branch.

**Comment by wizardofzos** [comment]
Indeed.... Weird.... Cannot reproduce anymore either?

Closing the issue
[2020-01-25 17-37-22.zip](https://github.com/wizardofzos/zigi/files/4112247/2020-01-25.17-37-22.zip)
