### ISSUE TITLE
Bug: If no site command table defined to ISPF

### ISSUE THREAD

**Issue by lbdyck** [wizardofzos/zigi#232]
If the installation does not define a site command table in the ISPF configuration (ISPCCONF) then the RFIND command table update will fail and thus not be usable.

Fix is to test and if no site command table then uses ISPCMDS.

Note: the update is only to the in-memory copy of the table so no permanent update occurs.

updated in lbdng branch

**Comment by wizardofzos** [comment]
Closed, as merged the v2r0-rc into master
