### ISSUE TITLE
Typos found in numerous panels after running spellc edit macro

### ISSUE THREAD

**Issue by lbdyck** [wizardofzos/zigi#233]
Updating the panels and will commit and push soon.  The panels in question are: ZIGICC    
ZIGIH110  
ZIGIH111  
ZIGIH120  
ZIGIH200  
ZIGIH260  
ZIGIH270  
ZIGIH280  
ZIGIH2D0  
ZIGIH330  
ZIGIH610  
ZIGIOREP

**Comment by wizardofzos** [comment]
Closed, as merged the v2r0-rc into master
