### ISSUE TITLE
Files in the github with extension are not pulled into the MVS datasets 

### ISSUE THREAD

**Issue by zszabo14** [wizardofzos/zigi#322]
Hi

As I tested, it the file in the repo has extension, like : jcl, sql. are not syncronized to the MVS dataset, but they are exists on the HFS. We are using external editors, like VS Code which recognizes the  file type ba it's extension. 
Could you please copy files with extension to PDS? eg WFDX012.JCL ---> WFDX012

Thank You!

**Comment by zszabo14** [comment]
1. I pushed a PDS to the repo.
2. I renamed one file (on github web) to .JCL
3. pulled to mainframe
4. the member as disappeared from the PDS

1. I created a file in git (on the web). named .jcl
2. pulled to mainframe
3 the file wasn't copied to the PDS.

**Comment by lbdyck** [comment]
At this time this is not the way that zigi works. Zigi was designed with the following constructs:

1. Each z/OS PDS causes an OMVS directory to be created with a directory name (upper case) that matches the z/OS dataset name excluding any prefixes (the ignore qualifier setting for the repository). Thus IBMUSER.TEST.PDS with an ignore qualifier of 1 would result in an OMVS directory of TEST.PDS.
2. Each z/OS PDS member is copied into the directory (1) with no extension and in upper case.
3. Sequential z/OS datasets are copied using the same conventions but to an OMVS file
4. During Clone/Pull/Replace processing the z/OS datasets are allocated thus:
   - A PDS is allocated as a PDSE V2 with the zigi wide default MAXGEN setting (default is 0 unless changed).
   - The space allocation is based on the calculated size of all the PDS member files.
   - The DCB is found in the .zigi/dsn file 

What you are asking for could be done and we encourage you to consider contributing to this project to provide this feature.

**Comment by lbdyck** [comment]
Some questions on how this might work and some potential issues.

zigi current maps the contents of a directory in the repository root to a PDS which means the files in the directory must conform to a  pds member name without an extension.

To support files with extension in a directory can be done by:
- remove extension when file is copied to z/OS
- keep a 'registry' that maps the z/OS dataset name and member names to desired file extension so when the member is copied to the subdirectory it is lowercased and the extension is added.

BUT what should be the process if in the directory are files with the same filename but different extensions - such as abc.c, abc.h, and abc.jcl ?  The PDS is unable to support 3 members with the same name but different contents.

It is also not a good practice to copy the directory files to different PDS based on the extension.

So - what's the right answer?

**Comment by zszabo14** [comment]
But your scenario doesn't even works now. Not only the PDS, but the windows directory cannot store more than 1 file  with same name. I think in most cases you have PDSs and you create a repo from them. In this scenario you couldn't have same member names. So, you (usually) have <hlq>.JCL, <hlq>.REXX, <hlq>.SQL, etc. Or if you want to have JCL, REXX, SQL in the same PDS you have to use different names anyway. This replicates to windows then you will have separate directories for JCL, REXX, SQL...etc.  
Only if you create a directory and files on your local machine, you can have abc.jcl, abc.rexx, abc.cbl. I think this is a rare case.

**Comment by lbdyck** [comment]
So you’re saying existing repositories wouldn’t need to be supported, only new repositories that are created using zigi?

**Comment by zszabo14** [comment]
No no, I just told, I think it's a rare scenario to have files/members with the same name in the same dir/PDS.  SO, you can add this as a limitation.
Btw, I found that in VS Code, z Open Development and Developer for Z are able to set file types on directories also. So you don't need extension to recognize the fily type for syntax check.

**Comment by lbdyck** [comment]
I'm just trying to understand the requirement. So if zigi support were to be implemented such that each PDS had a unique extension associated with it that would be adequate?

With what you found it appears that you don't need zigi to implement extensions at this time - is that accurate?

**Comment by zszabo14** [comment]
Ye

> 
> 
> I'm just trying to understand the requirement. So if zigi support were to be implemented such that each PDS had a unique extension associated with it that would be adequate?
+++ Yes 


> With what you found it appears that you don't need zigi to implement extensions at this time - is that accurate?
+++ Yes, you can put it in the backlog

**Comment by lbdyck** [comment]
Please advise if this would work for you.

![image](https://user-images.githubusercontent.com/42328411/77777133-17919200-701d-11ea-9269-554abf4d541d.png)

![image](https://user-images.githubusercontent.com/42328411/77777170-27a97180-701d-11ea-838c-266403add842.png)

**Comment by zszabo14** [comment]
Good job! Looks good to me!

(btw, what are your future plans for this tool? I'm asking as you know Rocket Software is also working on Git for Z and IBM's [DBB](https://github.com/IBM/dbb/tree/master/IDE/GitISPFClient) team also. )

**Comment by lbdyck** [comment]
future plans - unknown - depends upon where the need for new feature/function becomes visible to us and/or someone raises an issue.  How can zigi fit into the Git for Z project?

If you're ok with this update please close it.

thank you
