### ISSUE TITLE
[BUG] .zigi/<pds_name> is always comes in a new branch as changed if edited outside of zigi

### ISSUE THREAD

**Issue by zszabo14** [wizardofzos/zigi#327]
If I edit a mvs file outside of zigi, eg: in VS Code on my pc, then I pull the change in zigi, The file .zigi/<pds_name> is shown as unstaged change. 

> On branch SRS-100                                                          
> Your branch is up-to-date with 'origin/SRS-100'. 
> Changes not staged for commit:                                             
>   (use "git add <file>..." to update what will be committed)               
>   (use "git checkout -- <file>..." to discard changes in working 
> directory)                                
> .modified:   .zigi/JCL                                              
> no changes added to commit (use "git add" and/or "git commit -a")        

Until it's not committed, other branches cannot be checked out. 

> e   Cannot checkout branch.                             e
> e   M .zigi/JCL                                         e

Is it normal behavior?

> **(zigi v2r6)**

![image](https://user-images.githubusercontent.com/42870072/77547509-949df980-6ead-11ea-8122-221c9bdeda06.png)

**Comment by lbdyck** [comment]
Can you provide a step by step recreation scenario and I'll take a look (unless Henri has an idea)

**Comment by zszabo14** [comment]
1. create a repo with ZiGi and push to github
2, clone it onto your workstation
3, edit a file on windows
4, commit and push
5, pull with ZiGi
6, issue STATUS command in ZiGi

**Comment by lbdyck** [comment]
I don't have a workstation client per se so this is what I did:

1. verified the repo in zigi was up to date and clean
2. connected to github web 
3. edited a member of a pds on the web
4. saved and committed
5. back to zigi and did a pull
6. issued status and all is clean

I am using an updated zigi which may have resolved this issue as there was an issue with the ispf stats being updated properly.

Can you please try this branch https://github.com/lbdyck/zigi/tree/dev-tng and let us know?

thank you

**Comment by zszabo14** [comment]
Strange, I tested with web editor as you, and it produced the same issue.
I will ask our sysprog to update.

**Comment by lbdyck** [comment]
Be aware that the dev-tng branch from my github page is a development branch at this point.  It is subject to additional changes/updates.

**Comment by lbdyck** [comment]
can you confirm if this is resolved?

**Comment by zszabo14** [comment]
I haven't tested it yet. We cannot deploy DEV version, only 'stable' releases.
But you can close this.
