### ISSUE TITLE
[BUG] RM of membernames starting with - fails

### ISSUE THREAD

**Issue by mfsysprog** [wizardofzos/zigi#330]
**Describe the bug**
In earlier versions of zigi, members starting with a $member were converted into -member names.
When doing a RM on such a -member name, the panel will show *Removed, but the underlying git rm command fails with a 'Unknown switch I' error, since it is interpreting the -INDEX member name to be a -I NDEX switch. So it seems to me the -I should be escaped. I've tried a simple fix in usssafe function to escape the - as a \- and that works, but after that a subsequent RM will result in the panel selecting a wrong member (other than the one selected) - which could be another bug or something I'm doing wrong...

**To Reproduce**
1. Create a PDS with a $INDEX member
2. Create repo and add created PDS
3. manually rename in repo, i.e.: mv \$INDEX \-INDEX
4. add -INDEX (which works, )
5. put RM in front of -INDEX
6. panel will show '*Removed'
7. reenter the dataset and the -INDEX will still be in the 'added to index' state

**Expected behavior**
correctly run the git rm command.

**Comment by lbdyck** [comment]
A PDS member may not begin with a - so this shouldn't be an issue.  Can you explain how your PDS rename was done? The PDS member names must conform to z/OS naming standards which means the OMVS file copy of the PDS member must also.  (or it is early and I'm not understanding).

Please advise.

**Comment by mfsysprog** [comment]
Hello Lionel, 
Like I mentioned, when zigi still relied on cp -M to copy files, the $member would be converted on copy to -member in OMVS. So when I created a testrepo with an older zigi version that was the default behaviour. I guess with the new releases escaping the $ the best option is to remove the old repo and just rely on the fact that it cannot reappear again.

**Comment by lbdyck** [comment]
Yes - that is probably the best approach. Sorry about the incompatibility with this.
Please close this issue if you're ok with the solution.
