### ISSUE TITLE
[] Optional delete for z/os dataset when RM from repo

### ISSUE THREAD

**Issue by mfsysprog** [wizardofzos/zigi#331]
**Is your feature request related to a problem? Please describe.**
RM on a z/os dataset (and probably OMVS files too?) from a zigi repo will also implicitely delete the z/os dataset.

**Describe the solution you'd like**
I would like to see the z/os delete optional, like the option that is available when the full repo is removed.  

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by lbdyck** [comment]
This makes perfect sense - expect it in the next release.

**Comment by mfsysprog** [comment]
Thanks!

**Comment by lbdyck** [comment]
btw. this will work for a PS dataset but for a PDS member that member will be detected when the repo update check is run and will be copied to the OMVS filesystem and back to git. When removing a PS it is removed from git and also from zigi management.

How would you like this to work for a PDS member?  if the PDS member is deleted and the OMVS copy is not then it will be copied to OMVS the next time as if the member were a new member.  If the PDS member is not deleted but the OMVS file is, then zigi will remove the member from the PDS to keep the PDS and OMVS in sync.

**Comment by lbdyck** [comment]
do you use skype? if so I'd like to chat about this - you can find me on skype using my e-mail of lbdyck@gmail.com

**Comment by lbdyck** [comment]
How does this look for a dataset only - not sure how to deal with a PDS member at this point.

![image](https://user-images.githubusercontent.com/42328411/77903856-2d839a80-7249-11ea-9e12-796acaba4d54.png)

**Comment by lbdyck** [comment]
The rational behind this is:
1. the PDS member issue previously mentioned
2. removing from Git is fine but
3. if the OMVS file remains in the repository then it will be 'untracked' but Git will see it
4. keeping the z/OS dataset causes no zigi or git issues

**Comment by mfsysprog** [comment]
Hello Lionel, 
I understand the issue, let me think about it for a moment. 
I'll see if I can install skype after lunch

**Comment by wizardofzos** [comment]
Good to see you're on this Lionel :)

Also nice to see our 'Issue Templates' really seem to work :)
