### ISSUE TITLE
[BUG] zigi allows cloning using https but doesn't support it

### ISSUE THREAD

**Issue by mfsysprog** [wizardofzos/zigi#333]
**Describe the bug**
When cloning a repo, the panel allows (and accepts) specifying for example https://github.com/wizardofzos/zigi.git. But doing so will corrupt the flow that follows and the resulting repo.

**Release of zigi**
Which release of zigi are you reporting this bug against?
2.7 

**To Reproduce**
1. Execute clone command
2. Specify a https url for the remote
3. 
4. 

**Expected behavior**
Best option for now would be to restrict the url to a fully qualified ssh:// string.

**Screenshots**

**Additional context**
I've created a fix and have issues a pull request. The target is the master branch, not sure if that is desired...

**Comment by lbdyck** [comment]
How about instead of checking for ssh:// - check for https:// and reject that.

for example a clone on github with HTTPS gives this: https://github.com/wizardofzos/zigi.git

But for SSH you get this: git@github.com:wizardofzos/zigi.git

Thus a check for https:// would be specific solution that would not prevent the current practice of doing a copy/paste of the clone command from the git web servers.

**Comment by mfsysprog** [comment]
Turns out that the git clone over ssh has a 'relative path' format:
git clone -v git@github.com:mfsysprog/ZIGITEST.git

this format does not support having ssh:// in front:
git clone -v ssh://git@github.com:mfsysprog/ZIGITEST.git
Cloning into 'ZIGITEST'...                                                                                                            
FOTS1336 ssh: Could not resolve hostname github.com:mfsysprog: EDC9501I The name does not resolve for the supplied parameters.        
fatal: Could not read from remote repository.                                                                                         

if you use ssh:// in front, it must specify a absolute path to the repo, but since this is not the format that the 'copy function' for github provides (they provide relative path format) it must always be without the ssh://.

The parseGitURI function in it's current form does not (correctly) support the version with ssh:// in front. Also it assumes a format with a user@site:relatie/repo/ format:
parse var uri user '@' site ':' portorrealuser '/' repo 

So would the best option be to check for a @ and : in the url and make sure it does NOT start with ssh:// ??

**Comment by mfsysprog** [comment]
or go for the 'negative testing' route and make sure we don't allow https and hope users will specify the correct ssh format?

**Comment by lbdyck** [comment]
Check for https:// and reject it would be my thought.

**Comment by mfsysprog** [comment]
ok, I will implement that

**Comment by mfsysprog** [comment]
shall I also make sure that ssh:// is not specified, since it doesn't work properly atm?

**Comment by lbdyck** [comment]
if ssh:// doesn't work then prevent it as well - I'm a firm believer in helping to prevent someone from shooting themselves in the foot.

**Comment by mfsysprog** [comment]
I just realised this does mean that specifying an alternative port for the ssh connection is not possible. Doesn't seem like a bit issue for the github, gitlabs and bitbuckets available online, but it could present some issues for people using internal solution that have ssh running on a port other than 22.
So we might need to refactor this situation a bit more in the future.

**Comment by mfsysprog** [comment]
Ok, after reviewing the parseGitURI I see it does work properly. It just doesn't work if you put ssh:// in front of a 'scp like' url, like the one that github provides for copy. If it starts with ssh, than the part after the : is a port, and parseGitURI checks that correctly.
So I will just disable the http part.

**Comment by mfsysprog** [comment]
The interpretation is correct, but the flow gets corrupted. I'm going to create a different implementation of parseGitURI that hopefully will handle all ssh uri's as specified in https://git-scm.com/docs/git-clone correctly.

**Comment by mfsysprog** [comment]
fixed
