### ISSUE TITLE
[BUG] Status field for pds datasets

### ISSUE THREAD

**Issue by mfsysprog** [wizardofzos/zigi#366]
**Describe the bug**
Status field for pds dataset has status of first member with a change

**Release of zigi**
2.8

**To Reproduce**
1. In a repo with a PDS, select the pds 
2. Change and a single member
3. Change another member, but don't add
4. After PF3 back, the pds will have the status of the first member with a change. In this example [M ] Ready to commit, but if we did the above steps the other way around it will have [ M] Modified as the state.

**Expected behavior**
Suggestion is to give a status of 'Uncommitted changes' on the pds.
When subsequently selecting the pds, the indivual member will show the correct state for each individual member.

**Comment by wizardofzos** [comment]
Suggestion sounds solid :)

**Comment by mfsysprog** [comment]
working on it...
