### ISSUE TITLE
Code page troubles with zigi install

### ISSUE THREAD

**Issue by Hanspe-3019** [wizardofzos/zigi#370]
**problem**
Because our site's firewall rules prevent access from z/OS into internet, I am not able, to clone the zigi directory from github.  So I download a zip-file and transfer it to my windows work station. Then I upload the unzipped files into zOS zFS with simple windows ftp command line using sbd=1047. Execution of install.sh succeeds, but during testing I realize that the EBCDIC conversion of some of ISPF-panels went wrong, e.g. ZIGIEDIT attr Ü has become x'04', which is already defined and results in ISPF panel error. Obviously I did it the wrong way.   
**Solution I'd like**

- Please consider these elaborate code page pains in your installation doc.
- Provide ZIGI.EXEC and ZIGI.PANELS as binary XMIT file in the zigi repository.

Our ISPF is running with german code page, some braces like [] and {} are displayed ugly or even unreadable, but these characters are hard coded in the EXECs.

**Comment by lbdyck** [comment]
Go to http://www.cbttape.org/updates.htm and get file 997 for ZIGI 2.9 (should be posted in a day or so) or you can get the 2.8 release from http://www.cbttape.org/cbtdowns.htm - again in file 997. This packaging is in TSO XMIT format and should do what you want. This is one of the git challenges we have to overcome at some point.

let me know

**Comment by Hanspe-3019** [comment]
Posting the xmit-files at cbttape sounds good, that will work perfectly to me.
I will take a look at the use of special characters in ZIGI.EXEC which are problematic for non-English code pages. Maybe you can cleverly use global constants, which I just have to adjust in one place.
