### ISSUE TITLE
Improve file status messages for PDS - too generic

### ISSUE THREAD

**Issue by lbdyck** [wizardofzos/zigi#371]
The current status message for a PDS is too generic - need more granular.

Ideally have the most important to address to the least as the status.

**Comment by mfsysprog** [comment]
Hello Lionel, I did think about that, but I wasn't sure if there is a proper order. Do you have a suggestion?

**Comment by mfsysprog** [comment]
Ah, you already have a fix I see...

**Comment by mfsysprog** [comment]
Shouldn't you be looking at the first character of the stat field? 
https://git-scm.com/docs/git-status
If I understand your fix correctly it will look at both the 'X' and 'Y' position in the stat field, which could lead to ambiguous behaviour? Or I'm I understanding the change incorrectly?

**Comment by lbdyck** [comment]
I'm not convinced checking both X and Y would be significantly different - I could be wrong - I'm open to improvements as this was a 1st swag at it.  Same for the order.  My thinking was that the ?? and M were the most significant and the rest would fall into place. Being told there was untracked was important followed by modified  - both need to be git added. Having looked closer to the X/Y chart on that link perhaps the testing should be improved - feel free to enhance what I have here.

**Comment by mfsysprog** [comment]
I will see if I can find some time to test/adjust. It seems to me the last members state will decide the actual status, since filet.dsn /= null check will make sure that at least one previous state exists, but does not prevent the final member having a 'R' state overwriting a previously set 'M' state if I understand the code correctly. Before the code change, it would leave the loop when the first member of the pds was matched, now it will continue until the last (except when ?? is found).

**Comment by mfsysprog** [comment]
Actually, looking at the documentation for git-status again, I now noticed ' For paths that do not have merge conflicts, X shows the status of the index, and Y shows the status of the work tree'. So in fact, when you change a file, then git add it and subsequently do another edit I would expect a 'AM' state. In this case it would be best to show the file as modified I guess.

**Comment by lbdyck** [comment]
My logic may need tweaking and/or the ordering.  But you're correct an R would replace an M. I was more focused on getting it to process all members and get the stats correct (which wasn't as easy as it sounded at first - took several hours or trial and error and restarting).

**Comment by lbdyck** [comment]
You are correct Modified should be displayed.

**Comment by mfsysprog** [comment]
Yes, I understand your pain, it took me quite some time also to figure out what was going on. I was thinking about using the TRANSLATE instruction to convert states to ignore to a specific padding character. For example When TRANSLATE(filet.dsn,'MADC',,'$') = '$' whould indicate that one of the states MAD or C was set before so we should not set it to S. For C the test would be on MAD, etc.

**Comment by lbdyck** [comment]
That's interesting - i like it.  But I think the key also is which state should over-ride others.
Change to working tree should display over change in index. Perhaps it can be simplified with this sequence of tests:

?? = Untracked
X /= null then Modified
X = null and Y /= null then Ready to Commit

**Comment by lbdyck** [comment]
After re-reading the doc again - I noticed an I status for ignored. The code should test for ignored items as well.  That would be treated the same as ??.

**Comment by mfsysprog** [comment]
> That's interesting - i like it. But I think the key also is which state should over-ride others.
> Change to working tree should display over change in index. Perhaps it can be simplified with this sequence of tests:
> 
> ?? = Untracked
> X /= null then Modified
> X = null and Y /= null then Ready to Commit

https://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git

Shows an interesting option:
# Get number of files added to the index (but uncommitted)
expr $(git status --porcelain 2>/dev/null| grep "^M" | wc -l)

# Get number of files that are uncommitted and not added
expr $(git status --porcelain 2>/dev/null| grep "^ M" | wc -l)

So a 'M' in the X position indicates added but uncommitted, while 'M' in the Y position indicates unadded and uncommitted

**Comment by mfsysprog** [comment]
> After re-reading the doc again - I noticed an I status for ignored. The code should test for ignored items as well. That would be treated the same as ??.

_Ignored files are not listed, unless --ignored option is in effect, in which case XY are !!_
So if I read it correctly you must add --ignored to the command and in this case the !! will indicate the ignored file. They should not be handled like untracked files I guess, since ignored files have specifically been indicated to be ignored by git. The user actively indicated that they did not want them under version control.

**Comment by mfsysprog** [comment]
It seems to me that any state in the X position indicates a change that has been added and any state in the Y position indicates a change that has not been added. So we could count all the members with a non blank state in either position and create a general status for the whole pds from that. Something like [Xcount/Ycount] Ready to commit or [Xcount/Ycount] Working tree is dirty ?
Since a single member can have both changes the were added and changes still not added the combined count can be bigger than the actual amount of members.

**Comment by lbdyck** [comment]
I think we can ignore the ignore status. I’m not sure a count is worthwhile. 

This is looking better.

**Comment by mfsysprog** [comment]
No, probably the count doesn't really have added value.

**Comment by lbdyck** [comment]
What about this check:

?? - always mark untracked
[x ] - mark Ready to Commit 
[ x] - mark as Modified    

Would that be adequate - no counters and no mixed settings. Just the status that requires the highest attention?

**Comment by lbdyck** [comment]
Need to also update the current porcelain routine as [xM] results in Added to index and it should be Modified.

**Comment by lbdyck** [comment]
Try latest commit (tag = status_update)

**Comment by lbdyck** [comment]
Note: this obviously is not as granular as the individual members of a PDS but should suffice to provide the best info to the user about the state of the PDS (i could be wrong)

**Comment by mfsysprog** [comment]
Agree this seems the best option. Will try to test later.

**Comment by mfsysprog** [comment]
I've tested, but with your fix the first member will set the state (apart from untracked). 
Given the order - [??] Untracked, [ M] Modified, [M ] Ready to commit - the following code will do that:
 When stat = '??' then do 
      filet.dsn = stat 
      leave 
      end 
 When right(stat,1) /= ' ' 
      then filet.dsn = ' M' 
 When left(stat,1) /= ' ' & filet.dsn = null 
      then filet.dsn = 'M ' 

Any untracked member will set untracked and immediately leave the loop, so no other member states are processed. Any modified and not-added member can set the ' M' state. A modified and added member can only set the state, if there was no previously modified member. This way it will never override a 'modified and not-added' state.

**Comment by lbdyck** [comment]
This is the code that I have in it:

Select                                                
     When stat = '??' then do                         
          filet.dsn = stat                            
          leave                                       
          end                                         
     When right(stat,1) /= ' ' & filet.dsn = null     
          then filet.dsn = ' M'                       
     When left(stat,1) /= ' ' & filet.dsn = null      
          then filet.dsn = 'M '                       
     Otherwise nop                                    
     end                                              

That looks like what you posted. ???

**Comment by mfsysprog** [comment]
The issue is with the & filed.dsn = null for the second When statement. If there is a member with a 'Ready to commit state' it will set the pds state to that. If a subsequent modified, but not added member follows it will not override that state, because the filet.dsn is no longer null.

**Comment by lbdyck** [comment]
I see it now - thank you - will update shortly.
