### ISSUE TITLE
Remote repository name field not long enough for some URLs

### ISSUE THREAD

**Issue by jshewbert** [wizardofzos/zigi#374]
The remote repository field on the 'Clone Repository' screen (PANELID ZIGICC) is not long enough to contain some URLs.

It would be nice to have a zoom feature (F4 perhaps) that would allow you to enter URLs that are over 78 characters long.

I am currently using manual git commands to add the remote repository after creating a local repo.

**Comment by lbdyck** [comment]
Can you try a small change to the ZIGICC panel - delete the +'s that are indicated and let us know if that helps?

![image](https://user-images.githubusercontent.com/42328411/83542942-49155680-a4c1-11ea-9113-cc2953b87357.png)

**Comment by jshewbert** [comment]
That give me two lines to paste the remote repository URL. 

But the clone does not seem to work correctly. The current repository is not setup correctly:
![image](https://user-images.githubusercontent.com/37253795/83544046-4e779e80-a4cb-11ea-8ca3-af3abbd6d61f.png)

**Comment by lbdyck** [comment]
If the current repository is not in the zigi expected format then zigi will have challenges working with it.  See the ISPF tutorial or the PDF for info on the expected zigi repository layout.

Let me know .

**Comment by jshewbert** [comment]
I made a similar change to panel ZIGIREMO which allowed me to add a longer URL for the remote repository after creating a local repo. Creating the local repo first let ZIGI initialize it as a ZIGI managed repo.

**Comment by lbdyck** [comment]
Nice - i will update the devlbd branch with these changes.

**Comment by jshewbert** [comment]
FYI, I split the line 9 in ZIGIREMO to put the _origin variable on a line by itself. And then increased the size by moving the + all the way to the last column.

**Comment by lbdyck** [comment]
I also just updated the zigirepo panel so the display field for the url can scroll left/right if needed.

Please try out the devlbd branch and let us know.

**Comment by lbdyck** [comment]
> FYI, I split the line 9 in ZIGIREMO to put the _origin variable on a line by itself. And then increased the size by moving the + all the way to the last column.

I did it as a scrolling field instead :)
