### ISSUE TITLE
[PROB] 

### ISSUE THREAD

**Issue by mgrossmann** [wizardofzos/zigi#388]
Hi there,

got a problem with detecting changes in V3R02.
I did some changes in a pds member, but changes
are not detected by zigi.

Is there something I can do? e.g. reset stats?

Regards Mike

**Comment by lbdyck** [comment]
I noticed that as well when I was working on the 3.10 development release and believe I fixed it in that branch.  If you'd like to try that check it out at https://github.com/lbdyck/zigi

I'm hoping to get that out in a few weeks (or sooner)

**Comment by lbdyck** [comment]
Another workaround is to issue the CHECK command.  I've also found exiting and re-entering ZIGI for the repository sometimes resolves this.

**Comment by mgrossmann** [comment]
Hello Lionel,

the CHECK command doesn't find any change, as well.
But I will reinstall it from your repository, later this day.

Thank you
Mike

**Comment by cietpfm** [comment]
I believe [8d34f70 ](https://github.com/lbdyck/zigi/commit/8d34f701418590cf1244488b5ac3d12e0fec3826) is the relevant commit from branch [v3r10-dt](https://github.com/lbdyck/zigi/tree/v3r10-dt)

**Comment by mgrossmann** [comment]
actually this problem seems to be gone, ty
