### ISSUE TITLE
[BUG] VB datasets corrupted when added in binary mode

### ISSUE THREAD

**Issue by andrew890** [wizardofzos/zigi#395]
**Describe the bug**
If a VB dataset (sequential or partitioned) is added to Zigi in binary mode, the dataset is not copied correctly and the z/OS dataset created by Zigi when checking it out is corrupt.

**Release of zigi**
3.10

**To Reproduce**
1. Create a VB dataset e.g. LRECL=255
2. Add a line e.g. "Line 1"
3. Add another line e.g. "Line 2"
4. Add the dataset to Zigi in binary mode e.g. "AB" command, and commit.
5. Clone and check out the repository, or delete the DSN and replace it using Zigi
6. Line 1 and Line 2 are concatenated into a single line.

**Expected behavior**
The dataset is recreated with 2 records, the same as the original dataset.

**Additional context**
This kind of error is very common with programs copying variable length datasets to regular files. The RDW which describes the length of each record is stripped. Unfortunately the record length information is vital to reconstruct or even read the records.

Text files get around the problem by inserting record end markers e.g. newline in the data. This allows the records to be reconstructed, **as long as** the original data did not also contain any bytes matching the record end markers.

The length of each record must be recorded in the data when using variable length binary records. That could be in the IBM RDW format as used by the SITE RDW option in z/OS FTP (preferable in my opinion), or another format e.g. as used by the z/OSMF Dataset and File REST API.

**Comment by lbdyck** [comment]
I was able to recreate the issue with the VB datasets being in binary.  Now to find a solution. Suspect this is an issue with the cp command which is used for the copies to/from z/os and omvs.

**Comment by lbdyck** [comment]
sample cp command for a binary  vb file: cp -B  -U -v "//'LBD.TEST.FILE'" /u/lbd/git/testx/TEST.FILE 

This looks correct.  more digging needed.

**Comment by lbdyck** [comment]
I tried using oget and oput with the same issues (they apparently call cp under the covers) and I've found no cp option to correct the error, but I'm still looking.

**Comment by lbdyck** [comment]
Note that the copy from omvs to z/os uses oget in zigickot

**Comment by lbdyck** [comment]
and the oget specifies binary and looks good but the same results - still no valid copy from omvs to z/os for a binary vb file.

**Comment by lbdyck** [comment]
Per IBM this is just the way it is.  Here is a reference they pointed me to.

Thus for RECFM=V Binary files (PS and PDS) there is no viable option other than to convert them using TSO Transmit, or some other means, into a more portable format.

I'm sorry.

I will be updating the Add dataset routine to prevent these types of datasets from being added and provide an alert explaining why.

**Comment by andrew890** [comment]
If Zigi only works with FB datasets it is a major, major limitation.

It makes it very risky to use, because it means if you use Zigi in your project you create the restriction that your project can never use a RECFM=V dataset.

This would be simple to fix - you just need a custom program to copy the RECFM=V datasets correctly. I could do it easily in Java, but that would add a OMVS filesystem component which you said you don't want. I am sure it would be equally easy for a C programmer to create.

I'm disappointed but not surprised with IBMs answer. There are various IBM components which seem to have been written with no understanding of MVS-OS/390-z/OS dataset formats. I can't think of any example where breaking the data into chunks equal to the maximum variable record length would be correct, which is the documented behavior of the cp command.

**Comment by lbdyck** [comment]
Variable text work fine. Binary is the problem. 

Lionel B. Dyck <sdg ><
Website: www.lbdsoftware.com
Sent from my iPhone 12 Pro

Worry more about your character than your reputation.  Character is what you are, reputation merely what others think you are." - John Wooden

**Comment by andrew890** [comment]
Variable text works most of the time, except when it doesn't, i.e. you have a character in the data that breaks text mode. In that case it is useful to be able to process the dataset in binary.
There are actually 3 parts of the text processing that have requirements that have to be satisfied for text to work.
1. Copy from z/OS to OMVS
2. z/OS Git EBCDIC <-> ASCII/UTF8 etc translation
3. Regular git text processing e.g. line endings
So if you have a dataset in text mode, to put it in git and check it out again somewhere else, text mode processing has performed 6 translation steps. If there is something in the dataset that causes any of those steps to fail, your dataset is corrupted.

Any kind of text mode processing between dataset and filesystem, EBCDIC and ASCII where the data is altered is risky. The types of data that I am comfortable to do that with is very limited. You have to be very confident about what characters are in the data.

In general, binary processing is much safer.

**Comment by lbdyck** [comment]
we are mostly limited by the capabilities of the operating system utilities and how things will work across platforms. I'm open to a solution.

**Comment by andrew890** [comment]
We write software because we don't want to be limited by the OS utilities :-)

I have been playing with a Java program that could do the copy:
https://github.com/andrew890/zigi/blob/v3r10/java/src/main/java/rocks/zigi/CopyToFile.java

It takes a list of datasets and files and does them all, so it doesn't have to be invoked multiple times. It is likely to be much faster too.

Still needs to be enhanced to work with PDSes, and do the copy the other direction.

It could also do the text copies, if we have a specification of how text files should be handled? (Binary is much easier!)

**Comment by lbdyck** [comment]
I have confirmed that ZIGI is copying all sequential datasets to the OMVS file system in the 3.10 branch - i even added a popup to confirm the copy operation, although the speed of the copies and popups may be a bit fast to see all of them.

For speed check out http://dovetail.com/downloads/coz/index.html - the getpds and putpds, which are optional but now supported with ZIGI 3.10, are lightning fast for partitioned datasets and fully support ISPF member statistics along with both text and binary. It doesn't support load modules so standard cp is used for them, and they have the same challenge with vb-binary.

**Comment by andrew890** [comment]
getpds and putpds look good - when will they be incorporated into Zigi? They have the **-l rdw** option which is what you need to handle VB correctly. I'm not sure why that seems to be prohibited for binary though. Dovetailed are pretty good, I would expect them to handle VB binary correctly.
Could they extend getpds and putpds to handle sequential files?

**Comment by lbdyck** [comment]
ZIGI 3.10 supports dovetail if they are found in the path. The rdw option isn’t used right now. 

Lionel B. Dyck <sdg ><
Website: www.lbdsoftware.com
Sent from my iPhone 12 Pro

Worry more about your character than your reputation.  Character is what you are, reputation merely what others think you are." - John Wooden

**Comment by andrew890** [comment]
rdw (or l4 or mfrdw) is what is required for binary RECFM=V.
If you use dovetail, it would be worthwhile requiring it as a prerequisite.
Without it, Zigi requires a lot of patience for anything non-trivial.
